name: TestPyPI - Windows
# This workflow will upload a TestPyPI Python Package using Twine on demand (dispatch)

on: [ workflow_dispatch ]

permissions:
  contents: read

jobs:
  package_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build Source Package
        run: make src_dist

      - name: Publish Test Source Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_ARCHS_WINDOWS: AMD64 ARM64

      - name: List Packages
        continue-on-error: true
        run: ls wheelhouse/

      - uses: actions/upload-artifact@v4
        with:
          name: scanoss-wheels
          path: ./wheelhouse/*.whl

  upload_wheels:
    if: success()
    needs: [ build_wheels ]
    name: Upload wheels
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: scanoss-wheels
          path: wheelhouse

      - name: List Packages
        continue-on-error: true
        run: ls -la wheelhouse/

      - name: Publish Test Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages_dir: wheelhouse
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
