name: TestPyPI - Source
# This workflow will upload a TestPyPI Python Package for Source using Twine on demand (dispatch)

on: [ workflow_dispatch ]

permissions:
  contents: read

jobs:
  package_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build Source Package
        run: make src_dist

      - name: Publish Test Source Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
